// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactDocumentDataSlicesSlice = ComingSoonSlice | Hero2Slice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Title field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type NavigationDocumentDataSlicesSlice = NavigationItemSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Navigation List field in *Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_list
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  navigation_list: prismic.RichTextField;

  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | BannerFundatiaSincaSlice
  | ComingSoonSlice
  | LocationStatsSlice
  | FAskedQuestionsSlice
  | ProiecteRecenteSlice
  | HeroFullPhotoSlice
  | ImageCardsSlice
  | Hero2Slice
  | ContactButtonsSlice
  | ParteneriSlice
  | EchipaSlice
  | SixBoxesSlice
  | ImageWithStatsSlice
  | HeroSlice
  | GallerySlice
  | TextTwoColSlice
  | ProiecteNoiSlice
  | CustomerLogosSlice
  | QuoteSlice
  | TextSlice
  | TextWithImageSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Persoana documents
 */
interface PersoanaDocumentData {
  /**
   * Nume field in *Persoana*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: persoana.nume
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nume: prismic.KeyTextField;

  /**
   * Pozitie field in *Persoana*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: persoana.pozitie
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pozitie: prismic.KeyTextField;

  /**
   * Image field in *Persoana*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: persoana.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Order field in *Persoana*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: persoana.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;
}

/**
 * Persoana document from Prismic
 *
 * - **API ID**: `persoana`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PersoanaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PersoanaDocumentData>,
    "persoana",
    Lang
  >;

type ProiectDocumentDataSlicesSlice =
  | BannerFundatiaSincaSlice
  | ComingSoonSlice
  | TextSlice
  | Hero2Slice
  | TextTwoColSlice
  | GallerySlice
  | TextWithImageSlice;

/**
 * Content for Proiect documents
 */
interface ProiectDocumentData {
  /**
   * Title field in *Proiect*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: proiect.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Proiect*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: proiect.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Proiect*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: proiect.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Eyebrow field in *Proiect*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: proiect.eyebrow
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  eyebrow: prismic.RichTextField;

  /**
   * Slice Zone field in *Proiect*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: proiect.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProiectDocumentDataSlicesSlice> /**
   * Meta Description field in *Proiect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: proiect.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Proiect*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: proiect.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Proiect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: proiect.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Proiect document from Prismic
 *
 * - **API ID**: `proiect`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProiectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProiectDocumentData>,
    "proiect",
    Lang
  >;

/**
 * Item in *Settings → Socials*
 */
export interface SettingsDocumentDataSocialsItem {
  /**
   * facebook field in *Settings → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].facebook
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook: prismic.LinkField;

  /**
   * instagram field in *Settings → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].instagram
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;

  /**
   * youtube field in *Settings → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].youtube
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  youtube: prismic.LinkField;

  /**
   * twitter field in *Settings → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].twitter
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter: prismic.LinkField;

  /**
   * tiktok field in *Settings → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].tiktok
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tiktok: prismic.LinkField;
}

type SettingsDocumentDataSlicesSlice = FooterLinksSlice;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;

  /**
   * logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Socials field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<Simplify<SettingsDocumentDataSocialsItem>>;

  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | ContactDocument
  | NavigationDocument
  | PageDocument
  | PersoanaDocument
  | ProiectDocument
  | SettingsDocument;

/**
 * Primary content in *BannerFundatiaSinca → Primary*
 */
export interface BannerFundatiaSincaSliceDefaultPrimary {
  /**
   * Title field in *BannerFundatiaSinca → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Image field in *BannerFundatiaSinca → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Description field in *BannerFundatiaSinca → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.primary.image_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  image_description: prismic.RichTextField;

  /**
   * Button field in *BannerFundatiaSinca → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField;

  /**
   * Button Label field in *BannerFundatiaSinca → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_label: prismic.RichTextField;
}

/**
 * Primary content in *BannerFundatiaSinca → Items*
 */
export interface BannerFundatiaSincaSliceDefaultItem {
  /**
   * How To Help Us Title field in *BannerFundatiaSinca → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.items[].how_to_help_us_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  how_to_help_us_title: prismic.RichTextField;

  /**
   * How To Help Us Paragraph field in *BannerFundatiaSinca → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.items[].how_to_help_us_paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  how_to_help_us_paragraph: prismic.RichTextField;
}

/**
 * Default variation for BannerFundatiaSinca Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerFundatiaSincaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerFundatiaSincaSliceDefaultPrimary>,
  Simplify<BannerFundatiaSincaSliceDefaultItem>
>;

/**
 * Primary content in *BannerFundatiaSinca → Primary*
 */
export interface BannerFundatiaSincaSliceImageRightPrimary {
  /**
   * Title field in *BannerFundatiaSinca → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Image field in *BannerFundatiaSinca → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Description field in *BannerFundatiaSinca → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.primary.image_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  image_description: prismic.RichTextField;

  /**
   * Button field in *BannerFundatiaSinca → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField;

  /**
   * Button Label field in *BannerFundatiaSinca → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_label: prismic.RichTextField;
}

/**
 * Primary content in *BannerFundatiaSinca → Items*
 */
export interface BannerFundatiaSincaSliceImageRightItem {
  /**
   * How To Help Us Title field in *BannerFundatiaSinca → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.items[].how_to_help_us_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  how_to_help_us_title: prismic.RichTextField;

  /**
   * How To Help Us Paragraph field in *BannerFundatiaSinca → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_fundatia_sinca.items[].how_to_help_us_paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  how_to_help_us_paragraph: prismic.RichTextField;
}

/**
 * Image Right variation for BannerFundatiaSinca Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerFundatiaSincaSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<BannerFundatiaSincaSliceImageRightPrimary>,
  Simplify<BannerFundatiaSincaSliceImageRightItem>
>;

/**
 * Slice variation for *BannerFundatiaSinca*
 */
type BannerFundatiaSincaSliceVariation =
  | BannerFundatiaSincaSliceDefault
  | BannerFundatiaSincaSliceImageRight;

/**
 * BannerFundatiaSinca Shared Slice
 *
 * - **API ID**: `banner_fundatia_sinca`
 * - **Description**: BannerFundatiaSinca
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerFundatiaSincaSlice = prismic.SharedSlice<
  "banner_fundatia_sinca",
  BannerFundatiaSincaSliceVariation
>;

/**
 * Primary content in *ComingSoon → Primary*
 */
export interface ComingSoonSliceDefaultPrimary {
  /**
   * Title field in *ComingSoon → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coming_soon.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for ComingSoon Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComingSoonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ComingSoonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ComingSoon*
 */
type ComingSoonSliceVariation = ComingSoonSliceDefault;

/**
 * ComingSoon Shared Slice
 *
 * - **API ID**: `coming_soon`
 * - **Description**: ComingSoon
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComingSoonSlice = prismic.SharedSlice<
  "coming_soon",
  ComingSoonSliceVariation
>;

/**
 * Primary content in *ContactButtons → Primary*
 */
export interface ContactButtonsSliceDefaultPrimary {
  /**
   * Title Whatsapp field in *ContactButtons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_buttons.primary.title_whatsapp
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_whatsapp: prismic.RichTextField;

  /**
   * Text Whatsapp field in *ContactButtons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_buttons.primary.text_whatsapp
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_whatsapp: prismic.RichTextField;

  /**
   * Phone Number field in *ContactButtons → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_buttons.primary.phone_number
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  phone_number: prismic.NumberField;

  /**
   * Title Email field in *ContactButtons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_buttons.primary.title_email
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_email: prismic.RichTextField;

  /**
   * Text Email field in *ContactButtons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_buttons.primary.text_email
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_email: prismic.RichTextField;

  /**
   * Email field in *ContactButtons → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_buttons.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;
}

/**
 * Default variation for ContactButtons Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactButtonsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactButtonsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactButtons*
 */
type ContactButtonsSliceVariation = ContactButtonsSliceDefault;

/**
 * ContactButtons Shared Slice
 *
 * - **API ID**: `contact_buttons`
 * - **Description**: ContactButtons
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactButtonsSlice = prismic.SharedSlice<
  "contact_buttons",
  ContactButtonsSliceVariation
>;

/**
 * Primary content in *CustomerLogos → Primary*
 */
export interface CustomerLogosSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *CustomerLogos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  eyebrowHeadline: prismic.RichTextField;

  /**
   * callToActionLabel field in *CustomerLogos → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * callToActionLink field in *CustomerLogos → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;
}

/**
 * Primary content in *CustomerLogos → Items*
 */
export interface CustomerLogosSliceDefaultItem {
  /**
   * image field in *CustomerLogos → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *CustomerLogos → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for CustomerLogos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerLogosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CustomerLogosSliceDefaultPrimary>,
  Simplify<CustomerLogosSliceDefaultItem>
>;

/**
 * Slice variation for *CustomerLogos*
 */
type CustomerLogosSliceVariation = CustomerLogosSliceDefault;

/**
 * CustomerLogos Shared Slice
 *
 * - **API ID**: `customer_logos`
 * - **Description**: CustomerLogos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerLogosSlice = prismic.SharedSlice<
  "customer_logos",
  CustomerLogosSliceVariation
>;

/**
 * Primary content in *Echipa → Primary*
 */
export interface EchipaSliceDefaultPrimary {
  /**
   * Eyebrow field in *Echipa → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: echipa.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Echipa → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: echipa.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Echipa → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: echipa.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Echipa Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EchipaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EchipaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Echipa*
 */
type EchipaSliceVariation = EchipaSliceDefault;

/**
 * Echipa Shared Slice
 *
 * - **API ID**: `echipa`
 * - **Description**: Echipa
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EchipaSlice = prismic.SharedSlice<"echipa", EchipaSliceVariation>;

/**
 * Primary content in *FAskedQuestions → Primary*
 */
export interface FAskedQuestionsSliceDefaultPrimary {
  /**
   * Title field in *FAskedQuestions → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: f_asked_questions.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *FAskedQuestions → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: f_asked_questions.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * contact link field in *FAskedQuestions → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: f_asked_questions.primary.contact_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contact_link: prismic.LinkField;
}

/**
 * Primary content in *FAskedQuestions → Items*
 */
export interface FAskedQuestionsSliceDefaultItem {
  /**
   * Question Title field in *FAskedQuestions → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: f_asked_questions.items[].question_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question_title: prismic.RichTextField;

  /**
   * Question Answer field in *FAskedQuestions → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: f_asked_questions.items[].question_answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question_answer: prismic.RichTextField;
}

/**
 * Default variation for FAskedQuestions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FAskedQuestionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FAskedQuestionsSliceDefaultPrimary>,
  Simplify<FAskedQuestionsSliceDefaultItem>
>;

/**
 * Slice variation for *FAskedQuestions*
 */
type FAskedQuestionsSliceVariation = FAskedQuestionsSliceDefault;

/**
 * FAskedQuestions Shared Slice
 *
 * - **API ID**: `f_asked_questions`
 * - **Description**: FAskedQuestions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FAskedQuestionsSlice = prismic.SharedSlice<
  "f_asked_questions",
  FAskedQuestionsSliceVariation
>;

/**
 * Primary content in *FooterLinks → Primary*
 */
export interface FooterLinksSliceDefaultPrimary {
  /**
   * Footer Description field in *FooterLinks → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.primary.footer_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_description: prismic.RichTextField;

  /**
   * Footer Title field in *FooterLinks → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.primary.footer_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_title: prismic.RichTextField;
}

/**
 * Primary content in *FooterLinks → Items*
 */
export interface FooterLinksSliceDefaultItem {
  /**
   * Option Title field in *FooterLinks → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.items[].option_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  option_title: prismic.RichTextField;

  /**
   * Option Link field in *FooterLinks → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.items[].option_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  option_link: prismic.LinkField;
}

/**
 * Default variation for FooterLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterLinksSliceDefaultPrimary>,
  Simplify<FooterLinksSliceDefaultItem>
>;

/**
 * Slice variation for *FooterLinks*
 */
type FooterLinksSliceVariation = FooterLinksSliceDefault;

/**
 * FooterLinks Shared Slice
 *
 * - **API ID**: `footer_links`
 * - **Description**: FooterLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLinksSlice = prismic.SharedSlice<
  "footer_links",
  FooterLinksSliceVariation
>;

/**
 * Primary content in *Gallery → Items*
 */
export interface GallerySliceDefaultItem {
  /**
   * Image field in *Gallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<GallerySliceDefaultItem>
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Button Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Background Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceHero2Primary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Button Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.linkText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkText: prismic.KeyTextField;

  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Hero - 2 variation for Hero Slice
 *
 * - **API ID**: `hero2`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHero2 = prismic.SharedSliceVariation<
  "hero2",
  Simplify<HeroSliceHero2Primary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceHero2;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Hero2 → Primary*
 */
export interface Hero2SliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *Hero2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero_2.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *Hero2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Hero2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * callToActionLabel field in *Hero2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * callToActionLink field in *Hero2 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;
}

/**
 * Default variation for Hero2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Hero2SliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero2 → Primary*
 */
export interface Hero2SliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *Hero2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero_2.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *Hero2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Hero2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * callToActionLabel field in *Hero2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * callToActionLink field in *Hero2 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;
}

/**
 * Image Right variation for Hero2 Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero2SliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<Hero2SliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *Hero2*
 */
type Hero2SliceVariation = Hero2SliceDefault | Hero2SliceImageRight;

/**
 * Hero2 Shared Slice
 *
 * - **API ID**: `hero_2`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero2Slice = prismic.SharedSlice<"hero_2", Hero2SliceVariation>;

/**
 * Primary content in *HeroFullPhoto → Primary*
 */
export interface HeroFullPhotoSliceDefaultPrimary {
  /**
   * cover photo field in *HeroFullPhoto → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_full_photo.primary.cover_photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_photo: prismic.ImageField<never>;
}

/**
 * Default variation for HeroFullPhoto Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroFullPhotoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroFullPhotoSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroFullPhoto → Primary*
 */
export interface HeroFullPhotoSliceHeroFullPhotoWithTextPrimary {
  /**
   * cover photo field in *HeroFullPhoto → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_full_photo.primary.cover_photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_photo: prismic.ImageField<never>;

  /**
   * cover photo title field in *HeroFullPhoto → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_full_photo.primary.cover_photo_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cover_photo_title: prismic.RichTextField;

  /**
   * contact us button field in *HeroFullPhoto → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_full_photo.primary.contact_us
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contact_us: prismic.LinkToMediaField;

  /**
   * contact us label field in *HeroFullPhoto → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_full_photo.primary.contact_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact_label: prismic.RichTextField;
}

/**
 * Hero Full Photo With Text variation for HeroFullPhoto Slice
 *
 * - **API ID**: `heroFullPhotoWithText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroFullPhotoSliceHeroFullPhotoWithText =
  prismic.SharedSliceVariation<
    "heroFullPhotoWithText",
    Simplify<HeroFullPhotoSliceHeroFullPhotoWithTextPrimary>,
    never
  >;

/**
 * Slice variation for *HeroFullPhoto*
 */
type HeroFullPhotoSliceVariation =
  | HeroFullPhotoSliceDefault
  | HeroFullPhotoSliceHeroFullPhotoWithText;

/**
 * HeroFullPhoto Shared Slice
 *
 * - **API ID**: `hero_full_photo`
 * - **Description**: HeroFullPhoto
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroFullPhotoSlice = prismic.SharedSlice<
  "hero_full_photo",
  HeroFullPhotoSliceVariation
>;

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceBannerPrimary {
  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Banner variation for Image Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceBanner = prismic.SharedSliceVariation<
  "banner",
  Simplify<ImageSliceBannerPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceBanner;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *ImageCards → Primary*
 */
export interface ImageCardsSliceDefaultPrimary {
  /**
   * Heading field in *ImageCards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *ImageCards → Items*
 */
export interface ImageCardsSliceDefaultItem {
  /**
   * Image field in *ImageCards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *ImageCards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *ImageCards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Button Text field in *ImageCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;
}

/**
 * Default variation for ImageCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageCardsSliceDefaultPrimary>,
  Simplify<ImageCardsSliceDefaultItem>
>;

/**
 * Slice variation for *ImageCards*
 */
type ImageCardsSliceVariation = ImageCardsSliceDefault;

/**
 * ImageCards Shared Slice
 *
 * - **API ID**: `image_cards`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSlice = prismic.SharedSlice<
  "image_cards",
  ImageCardsSliceVariation
>;

/**
 * Primary content in *ImageWithStats → Primary*
 */
export interface ImageWithStatsSliceDefaultPrimary {
  /**
   * image field in *ImageWithStats → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_stats.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ImageWithStats → Items*
 */
export interface ImageWithStatsSliceDefaultItem {
  /**
   * stats field in *ImageWithStats → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_stats.items[].stats
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  stats: prismic.RichTextField;
}

/**
 * Default variation for ImageWithStats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithStatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageWithStatsSliceDefaultPrimary>,
  Simplify<ImageWithStatsSliceDefaultItem>
>;

/**
 * Slice variation for *ImageWithStats*
 */
type ImageWithStatsSliceVariation = ImageWithStatsSliceDefault;

/**
 * ImageWithStats Shared Slice
 *
 * - **API ID**: `image_with_stats`
 * - **Description**: ImageWithStats
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithStatsSlice = prismic.SharedSlice<
  "image_with_stats",
  ImageWithStatsSliceVariation
>;

/**
 * Primary content in *LocationStats → Primary*
 */
export interface LocationStatsSliceDefaultPrimary {
  /**
   * Title field in *LocationStats → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_stats.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *LocationStats → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_stats.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Background Image field in *LocationStats → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: location_stats.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Primary content in *LocationStats → Items*
 */
export interface LocationStatsSliceDefaultItem {
  /**
   * Project Title field in *LocationStats → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_stats.items[].project_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_title: prismic.RichTextField;

  /**
   * Location field in *LocationStats → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_stats.items[].location
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  location: prismic.RichTextField;
}

/**
 * Default variation for LocationStats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationStatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LocationStatsSliceDefaultPrimary>,
  Simplify<LocationStatsSliceDefaultItem>
>;

/**
 * Slice variation for *LocationStats*
 */
type LocationStatsSliceVariation = LocationStatsSliceDefault;

/**
 * LocationStats Shared Slice
 *
 * - **API ID**: `location_stats`
 * - **Description**: LocationStats
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationStatsSlice = prismic.SharedSlice<
  "location_stats",
  LocationStatsSliceVariation
>;

/**
 * Primary content in *NavigationItem → Primary*
 */
export interface NavigationItemSliceDefaultPrimary {
  /**
   * Name field in *NavigationItem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Link field in *NavigationItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *NavigationItem → Items*
 */
export interface NavigationItemSliceDefaultItem {
  /**
   * Child Name field in *NavigationItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.items[].child_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  child_name: prismic.RichTextField;

  /**
   * Child Link field in *NavigationItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.items[].child_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  child_link: prismic.LinkField;
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationItemSliceDefaultPrimary>,
  Simplify<NavigationItemSliceDefaultItem>
>;

/**
 * Slice variation for *NavigationItem*
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: NavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSlice = prismic.SharedSlice<
  "navigation_item",
  NavigationItemSliceVariation
>;

/**
 * Primary content in *Parteneri → Primary*
 */
export interface ParteneriSliceDefaultPrimary {
  /**
   * Title field in *Parteneri → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parteneri.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Parteneri → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parteneri.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * review field in *Parteneri → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parteneri.primary.review
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  review: prismic.RichTextField;
}

/**
 * Primary content in *Parteneri → Items*
 */
export interface ParteneriSliceDefaultItem {
  /**
   * Image field in *Parteneri → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: parteneri.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *Parteneri → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: parteneri.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Parteneri Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParteneriSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ParteneriSliceDefaultPrimary>,
  Simplify<ParteneriSliceDefaultItem>
>;

/**
 * Slice variation for *Parteneri*
 */
type ParteneriSliceVariation = ParteneriSliceDefault;

/**
 * Parteneri Shared Slice
 *
 * - **API ID**: `parteneri`
 * - **Description**: Parteneri
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParteneriSlice = prismic.SharedSlice<
  "parteneri",
  ParteneriSliceVariation
>;

/**
 * Primary content in *ProiecteNoi → Primary*
 */
export interface ProiecteNoiSliceDefaultPrimary {
  /**
   * uid field in *ProiecteNoi → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: proiecte_noi.primary.uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;

  /**
   * Maximum field in *ProiecteNoi → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: proiecte_noi.primary.maximum
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  maximum: prismic.NumberField;
}

/**
 * Default variation for ProiecteNoi Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProiecteNoiSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProiecteNoiSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProiecteNoi*
 */
type ProiecteNoiSliceVariation = ProiecteNoiSliceDefault;

/**
 * ProiecteNoi Shared Slice
 *
 * - **API ID**: `proiecte_noi`
 * - **Description**: ProiecteNoi
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProiecteNoiSlice = prismic.SharedSlice<
  "proiecte_noi",
  ProiecteNoiSliceVariation
>;

/**
 * Primary content in *ProiecteRecente → Primary*
 */
export interface ProiecteRecenteSliceDefaultPrimary {
  /**
   * title field in *ProiecteRecente → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: proiecte_recente.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *ProiecteRecente → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: proiecte_recente.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * background image field in *ProiecteRecente → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: proiecte_recente.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * about us field in *ProiecteRecente → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: proiecte_recente.primary.about_us
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  about_us: prismic.LinkField;

  /**
   * about us label field in *ProiecteRecente → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: proiecte_recente.primary.about_us_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_us_label: prismic.RichTextField;
}

/**
 * Primary content in *ProiecteRecente → Items*
 */
export interface ProiecteRecenteSliceDefaultItem {
  /**
   * project preview image field in *ProiecteRecente → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: proiecte_recente.items[].project_preview_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project_preview_image: prismic.ImageField<never>;

  /**
   * project title field in *ProiecteRecente → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: proiecte_recente.items[].project_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_title: prismic.RichTextField;

  /**
   * project short description field in *ProiecteRecente → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: proiecte_recente.items[].project_short_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_short_description: prismic.RichTextField;

  /**
   * project link field in *ProiecteRecente → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: proiecte_recente.items[].project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_link: prismic.LinkField;

  /**
   * project_link_label field in *ProiecteRecente → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: proiecte_recente.items[].project_link_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_link_label: prismic.RichTextField;
}

/**
 * Default variation for ProiecteRecente Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProiecteRecenteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProiecteRecenteSliceDefaultPrimary>,
  Simplify<ProiecteRecenteSliceDefaultItem>
>;

/**
 * Slice variation for *ProiecteRecente*
 */
type ProiecteRecenteSliceVariation = ProiecteRecenteSliceDefault;

/**
 * ProiecteRecente Shared Slice
 *
 * - **API ID**: `proiecte_recente`
 * - **Description**: ProiecteRecente
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProiecteRecenteSlice = prismic.SharedSlice<
  "proiecte_recente",
  ProiecteRecenteSliceVariation
>;

/**
 * Primary content in *Quote → Primary*
 */
export interface QuoteSliceDefaultPrimary {
  /**
   * Quote field in *Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Source field in *Quote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.primary.source
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  source: prismic.KeyTextField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>;

/**
 * Primary content in *SixBoxes → Primary*
 */
export interface SixBoxesSliceDefaultPrimary {
  /**
   * Title field in *SixBoxes → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: six_boxes.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * first field in *SixBoxes → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: six_boxes.primary.first
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  first: prismic.RichTextField;

  /**
   * second field in *SixBoxes → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: six_boxes.primary.second
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second: prismic.RichTextField;

  /**
   * third field in *SixBoxes → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: six_boxes.primary.third
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  third: prismic.RichTextField;

  /**
   * fourth field in *SixBoxes → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: six_boxes.primary.fourth
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fourth: prismic.RichTextField;

  /**
   * fifth field in *SixBoxes → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: six_boxes.primary.fifth
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fifth: prismic.RichTextField;

  /**
   * sixth field in *SixBoxes → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: six_boxes.primary.sixth
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sixth: prismic.RichTextField;
}

/**
 * Default variation for SixBoxes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SixBoxesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SixBoxesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SixBoxes*
 */
type SixBoxesSliceVariation = SixBoxesSliceDefault;

/**
 * SixBoxes Shared Slice
 *
 * - **API ID**: `six_boxes`
 * - **Description**: SixBoxes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SixBoxesSlice = prismic.SharedSlice<
  "six_boxes",
  SixBoxesSliceVariation
>;

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Title field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Main Photo field in *Text → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.main_photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_photo: prismic.ImageField<never>;

  /**
   * Paragraph Title field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.paragraph_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_title: prismic.RichTextField;

  /**
   * Embeded field in *Text → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.embeded
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  embeded: prismic.EmbedField;

  /**
   * Contact field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.contact
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact: prismic.RichTextField;

  /**
   * CEO field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.ceo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  ceo: prismic.RichTextField;
}

/**
 * Primary content in *Text → Items*
 */
export interface TextSliceDefaultItem {
  /**
   * Paragraph field in *Text → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  Simplify<TextSliceDefaultItem>
>;

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceTwoColumnsPrimary {
  /**
   * Text field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Two Columns variation for Text Slice
 *
 * - **API ID**: `twoColumns`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceTwoColumns = prismic.SharedSliceVariation<
  "twoColumns",
  Simplify<TextSliceTwoColumnsPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault | TextSliceTwoColumns;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *TextTwoCol → Primary*
 */
export interface TextTwoColSliceDefaultPrimary {
  /**
   * Title field in *TextTwoCol → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_two_col.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Eyebrow field in *TextTwoCol → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_two_col.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * First Column field in *TextTwoCol → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_two_col.primary.first_column
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  first_column: prismic.RichTextField;

  /**
   * Second Column field in *TextTwoCol → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_two_col.primary.second_column
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_column: prismic.RichTextField;

  /**
   * Background field in *TextTwoCol → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: text_two_col.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<
    "brand" | "brand-light" | "brand-lighter" | "brand-superlight"
  >;
}

/**
 * Default variation for TextTwoCol Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextTwoColSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextTwoColSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextTwoCol*
 */
type TextTwoColSliceVariation = TextTwoColSliceDefault;

/**
 * TextTwoCol Shared Slice
 *
 * - **API ID**: `text_two_col`
 * - **Description**: TextTwoCol
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextTwoColSlice = prismic.SharedSlice<
  "text_two_col",
  TextTwoColSliceVariation
>;

/**
 * Primary content in *TextWithImage → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
  /**
   * Text field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *TextWithImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextWithImage → Primary*
 */
export interface TextWithImageSliceWithButtonPrimary {
  /**
   * Text field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *TextWithImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Button Text field in *TextWithImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Image field in *TextWithImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Eyebrow field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  eyebrow: prismic.RichTextField;

  /**
   * Reverse field in *TextWithImage → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_with_image.primary.reverse
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  reverse: prismic.BooleanField;
}

/**
 * With Button variation for TextWithImage Slice
 *
 * - **API ID**: `withButton`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceWithButton = prismic.SharedSliceVariation<
  "withButton",
  Simplify<TextWithImageSliceWithButtonPrimary>,
  never
>;

/**
 * Slice variation for *TextWithImage*
 */
type TextWithImageSliceVariation =
  | TextWithImageSliceDefault
  | TextWithImageSliceWithButton;

/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
  "text_with_image",
  TextWithImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PersoanaDocument,
      PersoanaDocumentData,
      ProiectDocument,
      ProiectDocumentData,
      ProiectDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSocialsItem,
      SettingsDocumentDataSlicesSlice,
      AllDocumentTypes,
      BannerFundatiaSincaSlice,
      BannerFundatiaSincaSliceDefaultPrimary,
      BannerFundatiaSincaSliceDefaultItem,
      BannerFundatiaSincaSliceImageRightPrimary,
      BannerFundatiaSincaSliceImageRightItem,
      BannerFundatiaSincaSliceVariation,
      BannerFundatiaSincaSliceDefault,
      BannerFundatiaSincaSliceImageRight,
      ComingSoonSlice,
      ComingSoonSliceDefaultPrimary,
      ComingSoonSliceVariation,
      ComingSoonSliceDefault,
      ContactButtonsSlice,
      ContactButtonsSliceDefaultPrimary,
      ContactButtonsSliceVariation,
      ContactButtonsSliceDefault,
      CustomerLogosSlice,
      CustomerLogosSliceDefaultPrimary,
      CustomerLogosSliceDefaultItem,
      CustomerLogosSliceVariation,
      CustomerLogosSliceDefault,
      EchipaSlice,
      EchipaSliceDefaultPrimary,
      EchipaSliceVariation,
      EchipaSliceDefault,
      FAskedQuestionsSlice,
      FAskedQuestionsSliceDefaultPrimary,
      FAskedQuestionsSliceDefaultItem,
      FAskedQuestionsSliceVariation,
      FAskedQuestionsSliceDefault,
      FooterLinksSlice,
      FooterLinksSliceDefaultPrimary,
      FooterLinksSliceDefaultItem,
      FooterLinksSliceVariation,
      FooterLinksSliceDefault,
      GallerySlice,
      GallerySliceDefaultItem,
      GallerySliceVariation,
      GallerySliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceHero2Primary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceHero2,
      Hero2Slice,
      Hero2SliceDefaultPrimary,
      Hero2SliceImageRightPrimary,
      Hero2SliceVariation,
      Hero2SliceDefault,
      Hero2SliceImageRight,
      HeroFullPhotoSlice,
      HeroFullPhotoSliceDefaultPrimary,
      HeroFullPhotoSliceHeroFullPhotoWithTextPrimary,
      HeroFullPhotoSliceVariation,
      HeroFullPhotoSliceDefault,
      HeroFullPhotoSliceHeroFullPhotoWithText,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceBannerPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceBanner,
      ImageCardsSlice,
      ImageCardsSliceDefaultPrimary,
      ImageCardsSliceDefaultItem,
      ImageCardsSliceVariation,
      ImageCardsSliceDefault,
      ImageWithStatsSlice,
      ImageWithStatsSliceDefaultPrimary,
      ImageWithStatsSliceDefaultItem,
      ImageWithStatsSliceVariation,
      ImageWithStatsSliceDefault,
      LocationStatsSlice,
      LocationStatsSliceDefaultPrimary,
      LocationStatsSliceDefaultItem,
      LocationStatsSliceVariation,
      LocationStatsSliceDefault,
      NavigationItemSlice,
      NavigationItemSliceDefaultPrimary,
      NavigationItemSliceDefaultItem,
      NavigationItemSliceVariation,
      NavigationItemSliceDefault,
      ParteneriSlice,
      ParteneriSliceDefaultPrimary,
      ParteneriSliceDefaultItem,
      ParteneriSliceVariation,
      ParteneriSliceDefault,
      ProiecteNoiSlice,
      ProiecteNoiSliceDefaultPrimary,
      ProiecteNoiSliceVariation,
      ProiecteNoiSliceDefault,
      ProiecteRecenteSlice,
      ProiecteRecenteSliceDefaultPrimary,
      ProiecteRecenteSliceDefaultItem,
      ProiecteRecenteSliceVariation,
      ProiecteRecenteSliceDefault,
      QuoteSlice,
      QuoteSliceDefaultPrimary,
      QuoteSliceVariation,
      QuoteSliceDefault,
      SixBoxesSlice,
      SixBoxesSliceDefaultPrimary,
      SixBoxesSliceVariation,
      SixBoxesSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceDefaultItem,
      TextSliceTwoColumnsPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextSliceTwoColumns,
      TextTwoColSlice,
      TextTwoColSliceDefaultPrimary,
      TextTwoColSliceVariation,
      TextTwoColSliceDefault,
      TextWithImageSlice,
      TextWithImageSliceDefaultPrimary,
      TextWithImageSliceWithButtonPrimary,
      TextWithImageSliceVariation,
      TextWithImageSliceDefault,
      TextWithImageSliceWithButton,
    };
  }
}
