// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_buttons: dynamic(() => import("./ContactButtons")),
  customer_logos: dynamic(() => import("./CustomerLogos")),
  echipa: dynamic(() => import("./Echipa")),
  f_asked_questions: dynamic(() => import("./FAskedQuestions")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  hero_2: dynamic(() => import("./Hero2")),
  hero_full_photo: dynamic(() => import("./HeroFullPhoto")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  image_with_stats: dynamic(() => import("./ImageWithStats")),
  location_stats: dynamic(() => import("./LocationStats")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  parteneri: dynamic(() => import("./Parteneri")),
  proiecte_noi: dynamic(() => import("./ProiecteNoi")),
  proiecte_recente: dynamic(() => import("./ProiecteRecente")),
  quote: dynamic(() => import("./Quote")),
  six_boxes: dynamic(() => import("./SixBoxes")),
  text: dynamic(() => import("./Text")),
  text_two_col: dynamic(() => import("./TextTwoCol")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
